### ISSUE TITLE
review completed. 未完全滿足需求。

### ISSUE THREAD

**Issue by hatelove** [hashman/TDD_Day1_HW#1]
未完全滿足需求，請重新調整完畢後回覆issue.

調整建議如下：

1. 少了 N 筆一組的條件，要讓使用端可以自行決定幾筆一組。
1. 回傳的結果現在是 Items array, 代表呼叫端若要取用，得自行用 key 去取, 語意跟使用場景上，和 production code 直接 return 最後的 int array 結果是不同的。

**Comment by hashman** [comment]
Hi 91 哥 @hatelove 

已經調整完畢，再麻煩 91 哥 review 了，謝謝 91 哥

**Comment by hatelove** [comment]
great!
